# Generated by Django 5.0 on 2024-03-14 14:32

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0007_alter_trailer_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series_posters/')),
                ('main', models.BooleanField(default=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(to='movie.genrechoices')),
                ('quality', models.ManyToManyField(to='movie.qualitychoices')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration_time', models.TimeField()),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.series')),
            ],
        ),
    ]
