# Generated by Django 5.0 on 2024-03-17 11:39

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series_posters/')),
                ('card', models.ImageField(blank=True, null=True, upload_to='series_cards/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('main', models.BooleanField(default=True, null=True)),
                ('is_movie', models.BooleanField(default=False, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(to='movie.genrechoices')),
                ('quality', models.ManyToManyField(to='movie.qualitychoices')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration_time', models.TimeField()),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('card', models.ImageField(blank=True, null=True, upload_to='episodes_cards/')),
                ('video', models.FileField(null=True, upload_to='series/videos/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.series')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(verbose_name=django.core.validators.URLValidator(schemes='https'))),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.series')),
            ],
            options={
                'verbose_name': 'Serial Trailer',
                'verbose_name_plural': 'Serial Trailers',
            },
        ),
    ]
