# Generated by Django 5.0 on 2024-03-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='series_cards/'),
        ),
    ]
