# Generated by Django 5.0 on 2024-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_movie',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
