# Generated by Django 5.0 on 2024-03-15 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_series_is_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(verbose_name=django.core.validators.URLValidator(schemes='https'))),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.series')),
            ],
            options={
                'verbose_name': 'Serial Trailer',
                'verbose_name_plural': 'Serial Trailers',
            },
        ),
    ]
