# Generated by Django 5.0 on 2024-03-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_seriestrailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='episodes_cards/'),
        ),
    ]
