# Generated by Django 5.0 on 2024-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_episode_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.FileField(null=True, upload_to='series/videos/'),
        ),
    ]
