# Generated by Django 5.0 on 2024-03-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0009_remove_episode_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
