# Generated by Django 5.0 on 2024-03-12 02:12

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quality Choice',
                'verbose_name_plural': 'Quality Choices',
            },
        ),
        migrations.CreateModel(
            name='QualityChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quality Choice',
                'verbose_name_plural': 'Quality Choices',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('duration_time', models.TimeField()),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(to='movie.genrechoices')),
                ('quality', models.ManyToManyField(to='movie.qualitychoices')),
            ],
        ),
    ]
