# Generated by Django 5.0 on 2024-03-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrechoices',
            options={'verbose_name': 'Genre Choice', 'verbose_name_plural': 'Genre Choices'},
        ),
        migrations.AddField(
            model_name='movie',
            name='card_poster',
            field=models.ImageField(blank=True, null=True, upload_to='card_poster/'),
        ),
    ]
