# Generated by Django 5.0 on 2024-03-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_genrechoices_options_movie_card_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
