# Generated by Django 5.0 on 2024-03-14 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_trailer_trailer_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='movie',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie'),
        ),
    ]
