# Generated by Django 5.0 on 2024-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_trailer_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_movie',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
