# Generated by Django 5.0 on 2024-03-28 03:22

import apps.movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=apps.movie.models.VideoFileField(null=True, upload_to='movies/videos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.CharField(choices=[('Xitoy', 'Xitoy'), ('Hindiston', 'Hindiston'), ('Indoneziya', 'Indoneziya'), ('Braziliya', 'Braziliya'), ('Pakistan', 'Pakistan'), ('Nigeriya', 'Nigeriya'), ('Bangladesh', 'Bangladesh'), ('Rossiya', 'Rossiya'), ('Meksika', 'Meksika'), ('Yaponiya', 'Yaponiya'), ('Filippin', 'Filippin'), ('Eron', 'Eron'), ('Wietnam', 'Wietnam'), ('Tanzaniya', 'Tanzaniya'), ('Turkiya', 'Turkiya'), ('Kenya', 'Kenya'), ('Kolombiya', 'Kolombiya'), ('Ispaniya', 'Ispaniya'), ('Ukraina', 'Ukraina'), ('Uganda', 'Uganda'), ('Arjentina', 'Arjentina'), ('Zimbabve', 'Zimbabve'), ('Tayland', 'Tayland'), ('Almaniya', 'Almaniya'), ('Aljir', 'Aljir'), ('Polsha', 'Polsha'), ('Kanada', 'Kanada'), ('Marokash', 'Marokash'), ('Saudiya', 'Saudiya Arabistoni'), ('Uzbekiston', 'Uzbekiston'), ('Peru', 'Peru'), ('Malayziya', 'Malayziya'), ('Venesuela', 'Venesuela'), ('Ungariya', 'Ungariya'), ('Koreya', 'Koreya'), ('Amerika', 'Amerika')], max_length=200, null=True),
        ),
    ]
