# Generated by Django 5.0 on 2024-03-28 05:54

import apps.movie.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_video_alter_movie_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=apps.movie.models.VideoFileField(blank=True, null=True, upload_to='movies/videos/'),
        ),
    ]
