# Generated by Django 5.0 on 2024-03-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_is_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'verbose_name': 'Kino Trailer', 'verbose_name_plural': 'Kino Trailers'},
        ),
    ]
