# Generated by Django 5.0 on 2024-03-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Kino ', 'verbose_name_plural': 'Kinolar'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
    ]
