# Generated by Django 5.0 on 2024-03-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_options_remove_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
